### PR TITLE
Updated the top arrow in questions page

### PR DESCRIPTION
**Pull request by SadafKausar2025**
https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/137484958/38c82b45-89e5-41f1-9267-838781f25123

Screenshot 2024-05-17 211252

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Can you please assign me issue no #114?
and merge this PR

**Comment by Aryainguz** [comment]
@SadafKausar2025 please re sync repo to updated one then recreate the pr

**Comment by SadafKausar2025** [comment]
Hi @Aryainguz 
I have resolved the conflicts
Can you please merge this PR?

**Comment by SadafKausar2025** [comment]
hi @Aryainguz 
Can you please label this PR.

**Comment by Aryainguz** [comment]
Done @SadafKausar2025

**Comment by SadafKausar2025** [comment]
Ok , Thank You

**Comment by SadafKausar2025** [comment]
Hi @Aryainguz 
please label and assign in the issue as well  
this is the issue #114

**Pull request merged**
