### PR TITLE
change question layout

### PR DESCRIPTION
**Pull request by rudrakushwaha**
@Aryainguz I have changed the layout of questions by improving the CSS. Please review it and merge it with "hacktoberfest-accepted" label

### CODE REVIEW

**Comment by Aryainguz** [comment]
Great work @rudrakushwaha just please share the image of your changes once

**Comment by rudrakushwaha** [comment]
image
image
image
image

**Comment by Aryainguz** [comment]
Great work @rudrakushwaha

**Comment by rudrakushwaha** [comment]
@Aryainguz thank you

**Comment by rudrakushwaha** [comment]
@Aryainguz will this PR be counted for hacktoberfest?

**Comment by Aryainguz** [comment]
Yes it should but since only 3 days are left for October I’m not sure about
the waiting time yet for it

**Comment by rudrakushwaha** [comment]
image
waiting time will not be the issue I think. As the above message guarantees

**Pull request merged**
